#!/bin/bash

# $1 is kernel version
# $2 is the path to the kernel file
kernel_path=${2}
db_name_prefix="/etc/efi-keys/DB"

echo ${db_name_prefix}.key
sbsign --key ${db_name_prefix}.key --cert ${db_name_prefix}.crt --output ${kernel_path} ${kernel_path}
sbverify --cert ${db_name_prefix}.crt --list ${kernel_path}
sbverify --cert ${db_name_prefix}.crt ${kernel_path}
